---
  version: '3.4'
  services:
    weaviate:
      command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
      image: cr.weaviate.io/semitechnologies/weaviate:1.27.2
      ports:
      - 8080:8080
      - 50051:50051
      restart: on-failure:0
      environment:
        CONTEXTIONARY_URL: contextionary:9999
        QUERY_DEFAULTS_LIMIT: 25
        AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
        PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
        ENABLE_MODULES: 'text2vec-contextionary'
        DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
        CLUSTER_HOSTNAME: 'node1'
    contextionary:
      environment:
        OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
        EXTENSIONS_STORAGE_MODE: weaviate
        EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
        NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
        ENABLE_COMPOUND_SPLITTING: 'false'
      image: semitechnologies/contextionary:en0.16.0-v1.2.1
      ports:
      - 9999:9999
    newspublications:
      image: semitechnologies/weaviate-demo-newspublications:latest
      environment:
      - weaviate_host=http://weaviate.com:8080
      depends_on:
      - weaviate
      links:
        - "weaviate:weaviate.com"
...
