'''This code shows an example of using weaviate vector search without using any
modules. I have used SBERT to make my vectors and then loaded those in weaviate.
Here we can give a list of documents, map each of those to a vector using SBERT, 
and then use weaviate to store them. When a query comes in, we map the query with
SBERT to get a vector, and then weaviate finds the relevant document/text based on 
similarity score.'''

import pickle
import weaviate
import uuid
import datetime

def generate_uuid(class_name: str, identifier: str,
                  test: str = 'teststrong') -> str:
    """ Generate a uuid based on an identifier
    :param identifier: characters used to generate the uuid
    :type identifier: str, required
    :param class_name: classname of the object to create a uuid for
    :type class_name: str, required
    """
    test = 'overwritten'
    return str(uuid.uuid5(uuid.NAMESPACE_DNS, class_name + identifier))

def log(i: str) -> str:
    """ A simple logger
    :param i: the log message
    :type i: str
    """
    now = datetime.datetime.utcnow()
    print(now, "| " + str(i))

client = weaviate.Client("http://localhost:8080")
print("Client created")



from sentence_transformers import SentenceTransformer
# sbert_model = SentenceTransformer('bert-base-nli-mean-tokens'), Initially load using this, then start using pickle to save time.
with open("sbert",'rb') as f:
    sbert_model = pickle.load(f)

print("sbert loaded")

# I am adding the texts in this list,
# We can also add sentences of a large text individually to get more precise results when we query.
documents = [
    '''Taj mahal is an immense mausoleum of white marble, built in Agra between 1631 and 1648 by order of the Mughal emperor Shah Jahan in memory of his favourite wife, the Taj Mahal is the jewel of Muslim art in India and one of the universally admired masterpieces of the world's heritage.''',
    '''The Statue of Liberty is a 305-foot (93-metre) statue located on Liberty Island in Upper New York Bay, off the coast of New York City. The statue is a personification of liberty in the form of a woman. She holds a torch in her raised right hand and clutches a tablet in her left.''',
    '''The Statue of Liberty was sculpted between 1875 and 1884 under the direction of French sculptor Frédéric-Auguste Bartholdi, who began drafting designs in 1870. Bartholdi and his team hammered roughly 31 tons of copper sheets onto a steel frame. Before being mounted on its current pedestal, the statue stood over 151 feet (46 metres) tall and weighed 225 tons.''',
    '''Badminton is a racquet sport played using racquets to hit a shuttlecock across a net. Although it may be played with larger teams, the most common forms of the game are "singles" (with one player per side) and "doubles" (with two players per side). Badminton is often played as a casual outdoor activity in a yard or on a beach; formal games are played on a rectangular indoor court. Points are scored by striking the shuttlecock with the racquet and landing it within the opposing side's half of the court.''',
    '''James Bond is a fictional character created by novelist Ian Fleming in 1953.''',
    '''A British secret agent working for MI6 under the codename 007, he has been portrayed on film by actors Sean Connery, David Niven, George Lazenby, Roger Moore, Timothy Dalton, Pierce Brosnan and Daniel Craig in twenty-seven productions.'''
]

# A dictionary to store the document and its feature vector (the vector generated by SBERT)
doc_and_vec = {}

def giveVector(texts):
    # this function returns the vector using SBERT
    return sbert_model.encode(texts)

vectors = giveVector(documents)

for doc,vec in zip(documents,vectors):
    doc_and_vec[doc] = vec

print("vectors formed")

client.schema.delete_all()
class_obj = {
    "class": "Post",
    "vectorizer": "none", # we are providing the vectors ourselves through our SBERT model, so this field is none
    "properties": [{
        "name": "content",
        "dataType": ["text"],
    }]
}

client.schema.create_class(class_obj)
print("Schema class created")

for doc,vec in doc_and_vec.items():
    data_obj = {
    "content": doc
    }
    client.data_object.create(
    data_obj,
    "Post",
    generate_uuid('Post',doc),
    vector = vec,
    )
print("Finished importing data")

def process_query(vec):
    nearVector = {"vector": vec}
    res = client.query.get("Post", ["content", "_additional {certainty}"]).with_near_vector(nearVector).do()
    print(res)
    print("------------------------------------------------------------------------------------------------")
    print("-----------------------------------Most similar text -------------------------------------------")
    print(res['data']['Get']['Post'][0]['content'])
    print("------------------------------------------------------------------------------------------------")

while True:
    
    query = input("Enter query:")
    if query=='q':
        break

    query_vec = sbert_model.encode(query)
    process_query(query_vec)
